<?php
include_once ("Clases/Out_ProdOrdConf_Create_TT.php");
include_once ("Clases/AMB.php");
$out_prodordconf_create_tt = new Out_ProdOrdConf_Create_TT();
$OBJETO = 'Out_ProdOrdConf_Create_TT';
$SUBOBJETO=$OBJETO;
$amb = new AMB('Out_ProdOrdConf_Create_TT');
$CAMPOS = array('id','CONF_NO','ORDERID','SEQUENCE','OPERATION','SUB_OPER','CAPA_CATEGORY','SPLIT','FIN_CONF','CLEAR_RES','POSTG_DATE','DEV_REASON','CONF_TEXT','PLANT','WORK_CNTR','RECORDTYPE','CONF_QUAN_UNIT','CONF_QUAN_UNIT_ISO','YIELD','SCRAP','REWORK','CONF_ACTI_UNIT1','CONF_ACTI_UNIT1_ISO','CONF_ACTIVITY1','NO_REMN_ACTI1','CONF_ACTI_UNIT2','CONF_ACTI_UNIT2_ISO','CONF_ACTIVITY2','NO_REMN_ACTI2','CONF_ACTI_UNIT3','CONF_ACTI_UNIT3_ISO','CONF_ACTIVITY3','NO_REMN_ACTI3','CONF_ACTI_UNIT4','CONF_ACTI_UNIT4_ISO','CONF_ACTIVITY4','NO_REMN_ACTI4','CONF_ACTI_UNIT5','CONF_ACTI_UNIT5_ISO','CONF_ACTIVITY5','NO_REMN_ACTI5','CONF_ACTI_UNIT6','CONF_ACTI_UNIT6_ISO','CONF_ACTIVITY6','NO_REMN_ACTI6','CONF_BUS_PROC_UNIT1','CONF_BUS_PROC_UNIT1_ISO','CONF_BUS_PROC1','NO_REMN_BUS_PROC1','EXEC_START_DATE','EXEC_START_TIME','SETUP_FIN_DATE','SETUP_FIN_TIME','PROC_START_DATE','PROC_START_TIME','PROC_FIN_DATE','PROC_FIN_TIME','TEARDOWN_START_DATE','TEARDOWN_START_TIME','EXEC_FIN_DATE','EXEC_FIN_TIME','FCST_FIN_DATE','FCST_FIN_TIME','STD_UNIT1','STD_UNIT1_ISO','FORCAST_STD_VAL1','STD_UNIT2','STD_UNIT2_ISO','FORCAST_STD_VAL2','STD_UNIT3','STD_UNIT3_ISO','FORCAST_STD_VAL3','STD_UNIT4','STD_UNIT4_ISO','FORCAST_STD_VAL4','STD_UNIT5','STD_UNIT5_ISO','FORCAST_STD_VAL5','STD_UNIT6','STD_UNIT6_ISO','FORCAST_STD_VAL6','FORCAST_BUS_PROC_UNIT1','FORC_BUS_PROC_UNIT1_ISO','FORCAST_BUS_PROC_VAL1','PERS_NO','TIMEID_NO','WAGETYPE','SUITABILITY','NO_OF_EMPLOYEE','WAGEGROUP','BREAK_UNIT','BREAK_UNIT_ISO','BREAK_TIME','EX_CREATED_BY','EX_CREATED_DATE','EX_CREATED_TIME','TARGET_ACTI1','TARGET_ACTI2','TARGET_ACTI3','TARGET_ACTI4','TARGET_ACTI5','TARGET_ACTI6','TARGET_BUS_PROC1','EX_IDENT','LOGDATE','LOGTIME','WIP_BATCH','VENDRBATCH','ME_SFC_ID',);
$amb->cargarCampos($CAMPOS);
$amb->cargarTitulo('Datos de los campos en el Out_ProdOrdConf_Create_TT');
$amb->cargarTituloObjeto('un Out_ProdOrdConf_Create_TT');
switch ($accion) {
	case "editar$SUBOBJETO" :
		include_once ("editarObjeto.php");
		break;
	case "borrar$SUBOBJETO" :
		include_once ("borrarObjeto.php");
		break;
	case "alta$SUBOBJETO" :
		include_once ("altaObjeto.php");
		break;
	case $SUBOBJETO :
		include_once ("accionObjeto.php");
		include_once ("accionObjetoGuardar.php");
		break;
};

?>